### ISSUE TITLE
Wiki Seite VaultInterpreter

### ISSUE THREAD

**Issue by ocastx** [lucasbuschlinger/BachelorPraktikum#110]
Beschreibung:
-
Eine Wiki Seite für den VaultInterpreter, was er macht und wie man ihn benutzt um ein Plugin zu schreiben.

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

Akzeptanzkriterium:
-

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

(Geschätzter) Aufwand:
-
2 SP

[//]: # "------------Hier drüber eine Zeile frei!------------"
[//]: # "Zu Project und Milestone (Sprint) zugewiesen?"

**Comment by ghost** [comment]
# VaultInterpreter
Version 0.0.1
Classification: Interpreter

Overview
-----
The VaultInterpreter is an abstract class which all actual interpreter plugins inherit from. It is also a subclass of AbstractPlugin. It defines basic functionality needed by all interpreters, such as access to the database. Furthermore, the VaultInterpreter implements the Interpreter interface which specifies another function needed by all interpreters: The interpret function.

Creating a new interpreter plugin using the VaultInterpreter
-----
In order to create your own interpreter plugin you need to adhere to the above-mentioned structure. Specifically, every interpreter plugin needs to:

* be a subclass of VaultInterpreter
* implement the Interpreter interface
* provide an implementation for the function interpret(List<VaultEntry>)
* provide an implementation for all other abstract functions / functions declared in the implemented interfaces.

Additionally, you can configure your interpreter plugin in its property file if needed.

**Comment by ocastx** [comment]
Convert to Wiki Page and add to documentation

**Comment by lucasbuschlinger** [comment]
@ocastx page exists as sub of Interpreters

**Comment by ocastx** [comment]
Everything necessary explained, closed
