### ISSUE TITLE
Wiki Seite VaultExporter

### ISSUE THREAD

**Issue by ocastx** [lucasbuschlinger/BachelorPraktikum#111]
Beschreibung:
-
Eine Wiki Seite für den Vault Exporter, was er macht und wie man ihn benutzt um ein Plugin zu schreiben.

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

Akzeptanzkriterium:
-

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

(Geschätzter) Aufwand:
-
2 SP

[//]: # "------------Hier drüber eine Zeile frei!------------"
[//]: # "Zu Project und Milestone (Sprint) zugewiesen?"

**Comment by ghost** [comment]
# VaultExporter
Version 0.0.1
Classification: Exporter

Overview
-----
The VaultExporter is an abstract subclass of the AbstractExporter and a direct subclass of the CSVFileExporter. It provides a more specific implementation of the function prepareData and supports exporting VaultCsvEntries as .csv files.

Creating a new exporter plugin using the VaultExporter
-----
You can find the steps to create your own exporter plugin under the same section of the AbstractExporter wiki page. You are encouraged to take advantage of the existing hierarchy in order to save yourself work and to keep the project structured.

**Comment by ocastx** [comment]
Convert to Wiki Page and add to documentation

**Comment by ocastx** [comment]
https://github.com/lucasbuschlinger/BachelorPraktikum/wiki/Vault-Exporter
