### ISSUE TITLE
Wiki Seite FileExporter

### ISSUE THREAD

**Issue by ocastx** [lucasbuschlinger/BachelorPraktikum#112]
Beschreibung:
-
Eine Wiki Seite für den File Exporter, was er macht und wie man ihn benutzt um ein Plugin zu schreiben.

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

Akzeptanzkriterium:
-

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

(Geschätzter) Aufwand:
-
2 SP

[//]: # "------------Hier drüber eine Zeile frei!------------"
[//]: # "Zu Project und Milestone (Sprint) zugewiesen?"

**Comment by ghost** [comment]
# FileExporter
Version 0.0.1
Classification: Exporter

Overview
-----
The FileExporter is an abstract subclass of the AbstractExporter. The FileExporter provides an implementation for some of the functions which it inherits from the AbstractExporter, namely: exportDataToFile, writeToFile and prepareData.

Creating a new exporter plugin using the FileExporter
-----
You can find the steps to create your own exporter plugin under the same section of the AbstractExporter wiki page. You are encouraged to take advantage of the existing hierarchy in order to save yourself work and to keep the project structured.

**Comment by ocastx** [comment]
Convert to Wiki Page and add to documentation

**Comment by ocastx** [comment]
https://github.com/lucasbuschlinger/BachelorPraktikum/wiki/File-Exporter
