### ISSUE TITLE
Wiki Seite CSV File Exporter

### ISSUE THREAD

**Issue by ocastx** [lucasbuschlinger/BachelorPraktikum#113]
Beschreibung:
-
Eine Wiki Seite für den CSV File Exporter, was er macht und wie man ihn benutzt um ein Plugin zu schreiben.

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

Akzeptanzkriterium:
-

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

(Geschätzter) Aufwand:
-
2 SP

[//]: # "------------Hier drüber eine Zeile frei!------------"
[//]: # "Zu Project und Milestone (Sprint) zugewiesen?"

**Comment by ghost** [comment]
# CSVFileExporter
Version 0.0.1
Classification: Exporter

Overview
-----
The CSVFileExporter is an abstract subclass of the AbstractExporter and a direct subclass of the FileExporter. It provides a more specific implementation of the function writeToFile and supports exporting files in the .csv format.

Creating a new exporter plugin using the CSVFileExporter
-----
You can find the steps to create your own exporter plugin under the same section of the AbstractExporter wiki page. You are encouraged to take advantage of the existing hierarchy in order to save yourself work and to keep the project structured.

**Comment by ocastx** [comment]
Convert to Wiki Page and add to documentation

**Comment by ocastx** [comment]
https://github.com/lucasbuschlinger/BachelorPraktikum/wiki/CSV-File-Exporter
