### ISSUE TITLE
Wiki Seite AbstractExporter

### ISSUE THREAD

**Issue by ocastx** [lucasbuschlinger/BachelorPraktikum#114]
Beschreibung:
-
Eine Wiki Seite für den Abstract Exporter, was er macht und wie man ihn benutzt um ein Plugin zu schreiben.

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

Akzeptanzkriterium:
-

[//]: # "-----Hier drüber und drunter eine Zeile frei!-----"

(Geschätzter) Aufwand:
-
2 SP

[//]: # "------------Hier drüber eine Zeile frei!------------"
[//]: # "Zu Project und Milestone (Sprint) zugewiesen?"

**Comment by ghost** [comment]
# AbstractExporter
The AbstractExporter is the most abstract exporter class of the OpenDiabetes project. Almost all other abstract exporter classes as well as the actual exporter plugins inherit from this class. It is also a subclass of AbstractPlugin. 
The AbstractExporter declares two functions needed by all exporters: writeToFile and prepareData. 
Furthermore, it implements the Exporter interface which specifies two more functions needed by all exporters: setEntries and exportDataToFile.

Creating a new exporter plugin using the AbstractExporter
-----
In order to create your own exporter plugin you need to adhere to the above-mentioned structure. Specifically, every exporter plugin needs to:

* be a subclass of AbstractExporter
* implement the Exporter interface
* provide an implementation for the functions setEntries(List<?> entries) and exportDataToFile(String filepath, List<VaultEntry> data)
* provide an implementation for all other abstract functions / functions declared in the implemented interfaces.

Additionally, you can configure your exporter plugin in its property file if needed.

**Comment by ocastx** [comment]
Convert to Wiki Page and add to documentation

**Comment by ocastx** [comment]
https://github.com/lucasbuschlinger/BachelorPraktikum/wiki/Abstract-Exporter
